name: Deploy to Vercel
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install Vercel CLI
        run: npm i -g vercel
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install datasette datasette-sitemap datasette-block-robots datasette-backup datasette-search-all datasette-external-links-new-tabs datasette-copyable datasette-publish-vercel
      - name: Download db files
        run: |
          wget https://github.com/scillidan/database_csv/releases/latest/download/reference.db
          wget https://github.com/scillidan/database_csv/releases/latest/download/resource.db
          wget https://github.com/scillidan/database_csv/releases/latest/download/asset.db
      - name: Deploy Datasette using Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |-
          datasette publish vercel reference.db resource.db asset.db \
            --metadata metadata.yml \
            --token $VERCEL_TOKEN \
            --project datasette-site
